// Generated by CoffeeScript 1.9.3
(function() {
  var fs, mkdirp, path;

  path = require('path');

  mkdirp = require('mkdirp');

  fs = require('fs');

  module.exports = function(cwd, logPath, callback) {
    var dirname, filename, flags;
    filename = path.resolve(cwd, logPath);
    dirname = path.dirname(filename);
    flags = 'w';
    return mkdirp(dirname, function(error) {
      if (error != null) {
        return callback(error);
      }
      return fs.open(filename, flags, function(error, fd) {
        if (error != null) {
          return callback(error, {});
        }
        return callback(null, {
          filename: filename,
          fd: fd
        });
      });
    });
  };

}).call(this);
