// Generated by CoffeeScript 1.9.3
(function() {
  var createServer, findOpen, isAvailable, portscanner;

  createServer = require('net').createServer;

  portscanner = require('portscanner');

  isAvailable = function(port, callback) {
    return portscanner.checkPortStatus(port, '127.0.0.1', function(error, status) {
      if (error != null) {
        return callback(error);
      }
      return callback(null, status === 'closed');
    });
  };

  findOpen = function(port, callback) {
    var server;
    if (port == null) {
      port = 0;
    }
    server = createServer();
    server.on('error', function(error) {
      error.message = ("Checking port " + port + ":\n") + error.message;
      return callback(error);
    });
    return server.listen(port, function() {
      port = this.address().port;
      server.on('close', function() {
        return callback(null, port);
      });
      return server.close();
    });
  };

  module.exports = {
    isAvailable: isAvailable,
    findOpen: findOpen
  };

}).call(this);
