// Generated by CoffeeScript 1.9.3
(function() {
  var allProcs, fs, interpolatePort, killAllProcs, procNotFoundError, registerUncaughtHandler, registered, spawn;

  spawn = require('child_process').spawn;

  fs = require('fs');

  killAllProcs = function(procs) {
    procs.forEach(function(proc) {
      var err;
      try {
        return proc.rawProcess.kill();
      } catch (_error) {
        err = _error;
        return console.error(err.stack);
      }
    });
    return procs = [];
  };

  allProcs = [];

  registered = false;

  registerUncaughtHandler = function(proc) {
    allProcs.push(proc);
    if (!registered) {
      process.on('uncaughtException', function(error) {
        killAllProcs(allProcs);
        throw error;
      });
      process.on('exit', function() {
        return killAllProcs(allProcs);
      });
      return registered = true;
    }
  };

  procNotFoundError = function(error, cmd) {
    error.message = "Unable to find " + cmd;
    return error;
  };

  interpolatePort = function(port) {
    return function(arg) {
      return arg.replace('%port%', port);
    };
  };

  module.exports = function(name, command, commandArgs, port, logPath, logHandle, spawnOpts) {
    var child;
    commandArgs = commandArgs.map(interpolatePort(port));
    child = {
      rawProcess: spawn(command, commandArgs, spawnOpts),
      name: name,
      baseUrl: "http://127.0.0.1:" + port,
      port: port,
      logPath: logPath,
      logHandle: logHandle,
      launchCommand: command,
      launchArguments: commandArgs,
      workingDirectory: spawnOpts.cwd
    };
    registerUncaughtHandler(child);
    child.readLog = function(callback) {
      return fs.readFile(logPath, function(error, data) {
        if (error != null) {
          return callback(error);
        }
        return callback(null, data.toString());
      });
    };
    child.rawProcess.on('error', function(err) {
      if (err.errno === 'ENOENT') {
        child.error = procNotFoundError(err, command).stack;
      }
      return child.rawProcess.kill();
    });
    return child;
  };


  /*
  Copyright (c) 2015, Groupon, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:
  
  Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer.
  
  Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
  
  Neither the name of GROUPON nor the names of its contributors may be
  used to endorse or promote products derived from this software without
  specific prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   */

}).call(this);
