// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var child, cleanup, command, commandArgs, spawn, spawnOpts;

  spawn = require('child_process').spawn;

  child = null;

  cleanup = function() {
    if (child != null) {
      child.kill();
    }
    return child = null;
  };

  process.on('SIGTERM', cleanup);

  process.on('SIGINT', cleanup);

  process.on('SIGHUP', cleanup);

  process.on('exit', cleanup);

  process.on('disconnect', cleanup);

  process.on('uncaughtException', function(error) {
    cleanup();
    throw error;
  });

  command = process.argv[2];

  commandArgs = process.argv.slice(3);

  spawnOpts = {
    stdio: [0, 1, 2]
  };

  child = spawn(command, commandArgs, spawnOpts);

  child.on('exit', function(code) {
    child = null;
    return process.exit(code);
  });

  child.on('error', function(error) {
    if (error.code === 'ENOENT') {
      error.message = "ENOENT - Unable to find " + command;
    }
    throw error;
  });

}).call(this);
